# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'

target 'FriendlyChatDemo-iOS' do
end
